### PR TITLE
Update due to security vulnerability

### PR DESCRIPTION
**Pull request by Meschreiber**
https://github.com/sparklemotion/nokogiri/issues/1915

### CODE REVIEW

**Comment by Haroenv** [comment]
the other PR #2 updates to a newer version, is there a reason we went with the lowest fixed version here?

**Comment by redox** [comment]
> the other PR #2 updates to a newer version, is there a reason we went with the lowest fixed version here?

No it's the opposite (or the same), isn't it?. Here it's `>= 1.10.4` in #2 it's `>= 1.10`

**Comment by Krinkle** [comment]
> > the other PR #2 updates to a newer version, is there a reason we went with the lowest fixed version here?
> 
> No it's the opposite (or the same), isn't it?. Here it's `>= 1.10.4` in #2 it's `>= 1.10`

No, the PR that was merged (this one) set it to `~> 1.10.4` instead of `>= 1.10.4`, which is strictly lower as it means it is unable to apply security updates from 1.11 and other minor-compatible releases, which is why jekyll-algolia is now raising security warnings again.

**Comment by Krinkle** [comment]
> > the other PR #2 updates to a newer version, is there a reason we went with the lowest fixed version here?
> 
> No it's the opposite (or the same), isn't it?. Here it's `>= 1.10.4` in #2 it's `>= 1.10`

@redox The PR that was merged (this one) indeed suggested `>= 1.10.4`, however it looks like @Meschreiber overwrite this in a forced pushed commit (a67821a401f) on the main branch and set it to `~> 1.10.4` instead, which is strictly lower. This means security updates from 1.11 and other minor-compatible releases are not applies and thus jekyll-algolia is now raising security warnings again.

**Comment by Meschreiber** [comment]
Right you are @Krinkle , I don't know what I was thinking when I pushed that. I'm sorry about that.
Here's a PR that changes it to `>= 1.10.4` instead of `~> 1.10.4`. https://github.com/algolia/html-extractor/pull/6 
@redox, could you please approve when you get a chance?

**Pull request merged**
